source 'https://rubygems.org'

# Web framework and server
gem 'sinatra'
gem 'puma'

# Database
gem 'sequel'
gem 'sqlite3'

# Authentication
gem 'bcrypt'
gem 'warden'
gem 'rack-session'

# Markdown rendering (replaces Jekyll's build step)
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'rouge'

group :test do
  gem 'rack-test'
  gem 'minitest'
end
