source 'https://rubygems.org'

gem 'sinatra'
gem 'puma'
gem 'sequel'
gem 'sqlite3'
gem 'bcrypt'
gem 'warden'
gem 'rack-session'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'rouge'

group :test do
  gem 'rack-test'
  gem 'minitest'
end
